development:
    projetos:
      submissao_pdi: 1
    tipos:
      proposta_projeto: 1
      orcamento: 2
      acao: 3
    status:
      nao_avaliado: 1
      aprovado: 2
      reprovado: 3
    prioridade:
      normal: 1
      alta: 2
      baixa: 3
      urgente: 4
    custom_fields_id:
      iduff_solicitante: 2
      vinculo: 3
      setor_proponente: 4
      responsavel_projeto: 5

homologacao:
    projetos:
      submissao_pdi: 298
    tipos:
      proposta_projeto: 18
      orcamento: 19
      acao: 20
    status:
      nao_avaliado: 31
      aprovado: 32
      reprovado: 33
    prioridade:
      normal: 2
      alta: 3
      baixa: 1
      urgente: 4
    custom_fields_id:
      iduff_solicitante: 33
      vinculo: 34
      setor_proponente: 41
      responsavel_projeto: 42

test:
    projetos:
      submissao_pdi: 1
    tipos:
      proposta_projeto: 1
      orcamento: 2
      acao: 3
    status:
      nao_avaliado: 1
      aprovado: 2
      reprovado: 3
    prioridade:
      normal: 1
      alta: 2
      baixa: 3
      urgente: 4
    custom_fields_id:
      iduff_solicitante: 2
      vinculo: 3
      setor_proponente: 4
      responsavel_projeto: 5

production:
    projetos:
      submissao_pdi: 79
    tipos:
      proposta_projeto: 9
      orcamento: 8
      acao: 4
    status:
      nao_avaliado: 7
      aprovado: 8
      reprovado: 9
    prioridade:
      normal: 2
      alta: 3
      baixa: 1
      urgente: 4
      imediata: 5
    custom_fields_id:
      iduff_solicitante: 20
      vinculo: 21
      setor_proponente: 22
      responsavel_projeto: 23